networks:
  my-mixnet-dev-net:
    driver: bridge

services:
  # --- Destination Node (Bob) ---
  destination-bob:
    build: .
    container_name: destination-bob
    hostname: destination-bob
    networks:
      - my-mixnet-dev-net
    command: java -jar app.jar Destination BobDestination
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # --- Mix Node (Alpha) ---
  mixnode-alpha:
    build: .
    container_name: mixnode-alpha
    hostname: mixnode-alpha
    networks:
      - my-mixnet-dev-net
    command: java -jar app.jar Mix MixNode_Alpha
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mixnode-beta:
    build: .
    container_name: mixnode-beta
    hostname: mixnode-beta
    networks:
      - my-mixnet-dev-net
    command: java -jar app.jar Mix MixNode_Beta
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mixnode-gamma:
    build: .
    container_name: mixnode-gamma
    hostname: mixnode-gamma
    networks:
      - my-mixnet-dev-net
    command: java -jar app.jar Mix MixNode_Gamma
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # --- Client Node (Alice) ---
  client-a:
    build: .
    container_name: client-a
    hostname: client-a
    networks:
      - my-mixnet-dev-net
    command: java -jar app.jar Client AliceClient
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"