version: '3.8'

networks:
  my-mixnet-dev-net:
    driver: bridge

services:
  # --- Destination Node (Bob) ---
  destination-bob:
    build: .
    container_name: destination-bob
    hostname: destination-bob
    networks:
      - my-mixnet-dev-net
    # Command: java -jar app.jar <node_id> <node_type>
    command: java -jar Peer2Peer-1.0-SNAPSHOT.jar BobDestination Destination
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # --- Mix Node (Alpha) ---
  mixnode-alpha:
    build: .
    container_name: mixnode-alpha
    hostname: mixnode-alpha
    networks:
      - my-mixnet-dev-net
    # Command: java -jar app.jar <node_id> <node_type>
    command: java -jar Peer2Peer-1.0-SNAPSHOT.jar MixNode_Alpha Mix
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # --- Client Node (Alice) ---
  client-a:
    build: .
    container_name: client-a
    hostname: client-a
    networks:
      - my-mixnet-dev-net
    # Command: java -jar app.jar <node_id> <node_type>
    command: java -jar Peer2Peer-1.0-SNAPSHOT.jar AliceClient Client
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"